version: '3'
services:
  json-server:
    image: node:20-alpine
    working_dir: /data
    volumes:
      - ./data.json:/data/data.json
    command: npx json-server data.json --port 3000
    ports:
      - '3000:3000'

  angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - json-server
